## 📌 Chapter 2 – Introduction to Theano (Özet)

### 2.1 What is Theano?

* Theano, **Python için sayısal hesaplama kütüphanesi**.
* CPU veya GPU üzerinde çalışabiliyor.
* Özellikle **büyük yapay sinir ağı hesaplamaları** için tasarlanmış.
* 2007’de Montreal Üniversitesi (Yoshua Bengio’nun ekibi) tarafından geliştirildi.
* Sembolik ifadeleri tanımlayıp sonra derleyerek (compile) çok hızlı çalıştırabiliyor.

### 2.2 How to Install Theano

* Çalışan bir **Python + SciPy** ortamı gerekiyor.
* Kurulum:

In [1]:
!pip install pytensor

- Güncelleme:

In [2]:
!pip install --upgrade --no-deps pytensor

- En güncel sürümü GitHub’dan da yüklenebilir.
- CPU üzerinde çalışmak yeterli ama GPU için ek ayar yapılabiliyor.

### 2.3 Simple Theano Example

Kitaptaki ilk kod örneği 👇

In [3]:
# Theano örneği
import pytensor
from pytensor import tensor

# iki sembolik float sayı tanımla
a = tensor.dscalar()
b = tensor.dscalar()

# sembolik ifade
c = a + b

# ifadeyi derleyip fonksiyon haline getir
f = pytensor.function([a, b], c)

# gerçek değerler verip çalıştır
result = f(1.5, 2.5)
print(result)  # çıktı: 4.0


WARNING (pytensor.configdefaults): g++ not available, if using conda: `conda install gxx`
WARNING (pytensor.configdefaults): g++ not detected!  PyTensor will be unable to compile C-implementations and will default to Python. Performance may be severely degraded. To remove this warning, set PyTensor flags cxx to an empty string.


4.0


🔎 **Notlarım:**

* Burada `a` ve `b` gerçek sayılar değil, **sembolik değişkenler**.
* `c = a + b` ifadesi doğrudan çalışmaz, önce **Theano function** ile derlenir.
* Sonra `f(1.5, 2.5)` dediğinde, sembolik ifade gerçek hesaplamaya dönüşür.

### 2.4 Extensions and Wrappers for Theano

* Theano’yu direkt kullanmak yerine üstüne kurulmuş kütüphaneler var.
* En popüler olanı **Keras** → Theano’nun karmaşıklığını gizleyip kolay API sunuyor.
* Yani pratikte çoğunlukla Theano’yu doğrudan kullanmazsın.

### 2.5 More Theano Resources

* Theano’nun resmi sitesi, GitHub reposu ve ilgili makaleler listelenmiş.
* Ayrıca Theano üzerinde geliştirilmiş kütüphanelerin listesi de mevcut.

### 2.6 Summary

* Theano, derin öğrenmede temel sayısal altyapı kütüphanelerinden biri.
* Tek başına kullanılabilir ama daha pratik olması için Keras gibi wrapper’lar öneriliyor.


### 📌 Theano ile Matris Çarpımı Örneği

In [4]:
# Theano matris çarpımı örneği
import pytensor
import pytensor.tensor as T
import numpy as np

# sembolik matrisler tanımla
A = T.dmatrix('A')
B = T.dmatrix('B')

# matris çarpımını tanımla
C = T.dot(A, B)

# fonksiyon oluştur
f = pytensor.function([A, B], C)

# NumPy ile gerçek matrisler hazırla
a_val = np.array([[1, 2], [3, 4]])
b_val = np.array([[5, 6], [7, 8]])

# Theano fonksiyonunu çalıştır
result = f(a_val, b_val)
print(result)

[[19. 22.]
 [43. 50.]]


🔎 **Açıklamalar:**

- T.dmatrix → double precision (float64) matris tanımı.
- T.dot(A, B) → sembolik olarak matris çarpımını tanımlıyor.
- theano.function → sembolik ifadeyi gerçek fonksiyona çeviriyor.
- NumPy’den gelen matrisleri kullanıp sonucu hesaplıyoruz.

### 📌 Theano – Matris Transpoz ve Skaler İşlemler

In [5]:
import pytensor
import pytensor.tensor as T
import numpy as np

# sembolik matrisler
A = T.dmatrix('A')
B = T.dmatrix('B')

# 1) Transpoz işlemi
A_T = A.T

# 2) Skaler işlem: 2*A + B
expr = 2 * A + B

# fonksiyonlar oluştur
f_transpose = pytensor.function([A], A_T)
f_scalar = pytensor.function([A, B], expr)

# NumPy matrisleri
a_val = np.array([[1, 2], [3, 4]])
b_val = np.array([[5, 6], [7, 8]])

# çalıştır
print(f_transpose(a_val))

print("\n2*A + B:")
print(f_scalar(a_val, b_val))


[[1. 3.]
 [2. 4.]]

2*A + B:
[[ 7. 10.]
 [13. 16.]]


🔎 **Özet:**

* `A.T` → Theano’da transpoz işlemi.
* `2*A + B` → sembolik olarak skaler + matris kombinasyonu.
* Aynı yapı ile daha karmaşık lineer cebir işlemleri kurulabilir.