## 📌 Chapter 1 – Welcome (Özet)

### 1.1 Deep Learning the Wrong Way

* Çoğu uzman, “önce yıllarca lineer cebir, olasılık, istatistik, geleneksel makine öğrenmesi öğrenmelisin, hatta doktora yapmalısın” gibi tavsiyeler verir.
* Yazar bu yaklaşımı yanlış buluyor.
* Çünkü böyle düşünürsen **asıl model geliştirmeye başlamak için yıllar kaybedersin**.

### 1.2 Deep Learning With Python

* Bu kitapta yaklaşım **tam tersi**: Önce **uygulamalı olarak model geliştir**, sonra ilgini çekerse teoriye dal.
* Yazar Keras’ı seçmiş çünkü:

  * Hem Theano hem TensorFlow üzerinde çalışabiliyor.
  * Python’un güçlü ekosistemiyle entegre.
  * Basit ve hızlı prototipleme sağlıyor.
* Hedef: Okuyucu kitabın içinde ilerlerken kendi derin öğrenme modellerini geliştirip çalıştırabilsin.

### 1.3 Book Organization

Kitap 3 tür içerikten oluşuyor:

* **Lessons (Dersler):** Tek konu odaklı, kısa sürede yapılabilecek.
* **Projects (Projeler):** Birden fazla dersi birleştirerek uçtan uca çözümler.
* **Recipes (Tarifler):** Kitaptaki tüm kodları hazır olarak kullanabileceğin “copy-paste” yapılar.

Kitap şu parçalara ayrılmış:

1. **Background** – Theano, TensorFlow, Keras temeli + AWS kullanımı.
2. **Multilayer Perceptrons** – İlk ağ modelleri, performans değerlendirme, scikit-learn entegrasyonu.
3. **Advanced MLPs** – Model kaydetme, checkpointing, overfitting önleme, learning rate ayarlama.
4. **Convolutional Neural Networks** – Görüntü ve metin sınıflandırma projeleri.
5. **Recurrent Neural Networks** – Zaman serileri, LSTM, text generation projeleri.
6. **Conclusions** – Ek kaynaklar, destek bölümü.

### 1.4 Requirements For This Book

* Python 2.7 veya 3 (yazar Python 2.7.11 ile geliştirmiş).
* SciPy, NumPy, Matplotlib, Pandas, scikit-learn kurulu olmalı.
* Temel ML kavramlarına (cross-validation, one-hot encoding gibi) biraz aşinalık faydalı.
* GPU zorunlu değil, ama hız için AWS üzerinde GPU kullanımı öneriliyor.

### 1.5 Your Outcomes From Reading This Book

Bu kitabı bitirdiğinde şunları yapabiliyor olacaksın:

* Baştan sona kendi dataset’in üzerinde model kurup değerlendirmek.
* İleri seviye tekniklerle SOTA (state-of-the-art) sonuçlara yaklaşmak.
* Büyük modelleri görüntü ve metin verisine uygulamak.
* Görüntü augmentasyonu gibi ek tekniklerle performans artırmak.
* Nereden destek alabileceğini bilmek.

### 1.6 What This Book is Not

* **Derin öğrenme teorisi kitabı değil.** Formüller, algoritmaların iç matematiği yok.
* **Algoritma kitabı değil.** Amaç kod ve uygulama.
* **Python kitabı değil.** Python’u zaten biraz biliyor olman bekleniyor.

### 1.7 Summary

* Şu an derin öğrenmeye başlamak için en doğru zaman.
* Araçlar güçlü, öğrenme eğrisi hızlı.
* Bu kitap senin yolculuğunun başlangıcı olacak.

## 📌 Chapter 2 – Introduction to Theano (Özet)

### 2.1 What is Theano?

* Theano, **Python için sayısal hesaplama kütüphanesi**.
* CPU veya GPU üzerinde çalışabiliyor.
* Özellikle **büyük yapay sinir ağı hesaplamaları** için tasarlanmış.
* 2007’de Montreal Üniversitesi (Yoshua Bengio’nun ekibi) tarafından geliştirildi.
* Sembolik ifadeleri tanımlayıp sonra derleyerek (compile) çok hızlı çalıştırabiliyor.

### 2.2 How to Install Theano

* Çalışan bir **Python + SciPy** ortamı gerekiyor.
* Kurulum:

In [1]:
!pip install pytensor

- Güncelleme:

In [2]:
!pip install --upgrade --no-deps pytensor

- En güncel sürümü GitHub’dan da yüklenebilir.
- CPU üzerinde çalışmak yeterli ama GPU için ek ayar yapılabiliyor.

### 2.3 Simple Theano Example

Kitaptaki ilk kod örneği 👇

In [3]:
# Theano örneği
import pytensor
from pytensor import tensor

# iki sembolik float sayı tanımla
a = tensor.dscalar()
b = tensor.dscalar()

# sembolik ifade
c = a + b

# ifadeyi derleyip fonksiyon haline getir
f = pytensor.function([a, b], c)

# gerçek değerler verip çalıştır
result = f(1.5, 2.5)
print(result)  # çıktı: 4.0


WARNING (pytensor.configdefaults): g++ not available, if using conda: `conda install gxx`
WARNING (pytensor.configdefaults): g++ not detected!  PyTensor will be unable to compile C-implementations and will default to Python. Performance may be severely degraded. To remove this warning, set PyTensor flags cxx to an empty string.


4.0


🔎 **Notlarım:**

* Burada `a` ve `b` gerçek sayılar değil, **sembolik değişkenler**.
* `c = a + b` ifadesi doğrudan çalışmaz, önce **Theano function** ile derlenir.
* Sonra `f(1.5, 2.5)` dediğinde, sembolik ifade gerçek hesaplamaya dönüşür.

### 2.4 Extensions and Wrappers for Theano

* Theano’yu direkt kullanmak yerine üstüne kurulmuş kütüphaneler var.
* En popüler olanı **Keras** → Theano’nun karmaşıklığını gizleyip kolay API sunuyor.
* Yani pratikte çoğunlukla Theano’yu doğrudan kullanmazsın.

### 2.5 More Theano Resources

* Theano’nun resmi sitesi, GitHub reposu ve ilgili makaleler listelenmiş.
* Ayrıca Theano üzerinde geliştirilmiş kütüphanelerin listesi de mevcut.

### 2.6 Summary

* Theano, derin öğrenmede temel sayısal altyapı kütüphanelerinden biri.
* Tek başına kullanılabilir ama daha pratik olması için Keras gibi wrapper’lar öneriliyor.


### 📌 Theano ile Matris Çarpımı Örneği

In [4]:
# Theano matris çarpımı örneği
import pytensor
import pytensor.tensor as T
import numpy as np

# sembolik matrisler tanımla
A = T.dmatrix('A')
B = T.dmatrix('B')

# matris çarpımını tanımla
C = T.dot(A, B)

# fonksiyon oluştur
f = pytensor.function([A, B], C)

# NumPy ile gerçek matrisler hazırla
a_val = np.array([[1, 2], [3, 4]])
b_val = np.array([[5, 6], [7, 8]])

# Theano fonksiyonunu çalıştır
result = f(a_val, b_val)
print(result)

[[19. 22.]
 [43. 50.]]


🔎 **Açıklamalar:**

- T.dmatrix → double precision (float64) matris tanımı.
- T.dot(A, B) → sembolik olarak matris çarpımını tanımlıyor.
- theano.function → sembolik ifadeyi gerçek fonksiyona çeviriyor.
- NumPy’den gelen matrisleri kullanıp sonucu hesaplıyoruz.

### 📌 Theano – Matris Transpoz ve Skaler İşlemler

In [5]:
import pytensor
import pytensor.tensor as T
import numpy as np

# sembolik matrisler
A = T.dmatrix('A')
B = T.dmatrix('B')

# 1) Transpoz işlemi
A_T = A.T

# 2) Skaler işlem: 2*A + B
expr = 2 * A + B

# fonksiyonlar oluştur
f_transpose = pytensor.function([A], A_T)
f_scalar = pytensor.function([A, B], expr)

# NumPy matrisleri
a_val = np.array([[1, 2], [3, 4]])
b_val = np.array([[5, 6], [7, 8]])

# çalıştır
print("Transpoz:")
print(f_transpose(a_val))

print("\n2*A + B:")
print(f_scalar(a_val, b_val))


Transpoz:
[[1. 3.]
 [2. 4.]]

2*A + B:
[[ 7. 10.]
 [13. 16.]]


🔎 **Özet:**

* `A.T` → Theano’da transpoz işlemi.
* `2*A + B` → sembolik olarak skaler + matris kombinasyonu.
* Aynı yapı ile daha karmaşık lineer cebir işlemleri kurulabilir.